### ISSUE TITLE
Dates in data.json as timestamp

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Redunda#32]
The data would be much easier to parse, if the dates `created_at` and `updated_at` would be UNIX-timestamps.

**Comment by ArtOfCode-** [comment]
I *think* the dates are ISO8601-compliant; I bet Java has a method to parse those.

**Comment by NobodyNada** [comment]
I've been thinking about this too.  While we currently use a standard format, Unix time is *much* easier to parse.  The only advantage I can think of for the current format is human-readability, which isn't much of a priority here.

**Comment by FelixSFD** [comment]
@ArtOfCode- Looks like the `Z` at the end is wrong and can't be parsed by Java:

```
java.time.format.DateTimeParseException: Text '2017-03-21T17:07:20.000Z' could not be parsed, unparsed text found at index 23
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at java.time.LocalDateTime.parse(LocalDateTime.java:477)
	at org.sobotics.redunda.DataService.syncFiles(DataService.java:326)
	at org.sobotics.guttenberg.clients.Client.main(Client.java:80)
```

**Comment by NobodyNada** [comment]
@FelixSFD `Z` means UTC; I'm not sure why Java doesn't know that.

**Comment by FelixSFD** [comment]
Okay. I've found a way to parse it by specifying the pattern manually.
